### PR TITLE
Fix untialized values

### PR DESCRIPTION
**Pull request by BramGiesen**
Some small fixes related to memory issues and some fixes related to the handling the MIDI input.

### CODE REVIEW

**Comment by dromer** [comment]
Been having some issues with the arpeggiator plugin, will try a build of your branch to see if it behaves better.

**Comment by dromer** [comment]
So, my main issue seems to resolve around external midi synchronization.
Even when filtering just midi-notes, mod-arpeggiator takes everything down when I run qtractor transport signals to control mod-host transport externally.
When I instead use jack_midi_clock to send transport messages things are fine.

So, even with `5fcd623414442d66f61d6b5237ed086fce2590a6` this happens for me, semi-reliably.

**Comment by BramGiesen** [comment]
Hi @dromer, I personally never tested this scenario, so it would be helpful if I can reproduce it to see if I can make some adjustments. Do you send the qtractor transport signal from your computer to a MOD Device running the arpeggiator? Or are you using a different kind of set-up?

**Comment by dromer** [comment]
Yes, so a computer running jack and qtractor playing midi (and some local synths, recordings). default "main" midi output into Duo X on USB and MOD slaved to midi transport.

The effect is mod-ui crashing/reloading at transport events start/stop and when putting the playhead back to the start of the daw.

**Comment by BramGiesen** [comment]
@dromer, I had a look with my setup and qtractor. I did found some few odd things while syncing with qtractor, although not all of that seems to be directly related to the arpeggiator, but I will do some more testing. I did found a regression regarding a all notes off command that was now not picked up and I changed the clock implementation a little so that it actually stops when the transport is not running. So far I'm not able to reproduce any mod-ui crashes / reloading ui, but as mentioned I will do some more testing. Which version of the mod-firmware and qtractor are you running?

**Comment by dromer** [comment]
Well you found something at least :)

I'm on the latest `1.10.2` and using qtractor `0.9.5` and had to build the plugin with the `modduox-static` toolchain, the default failed to build somehow.

Will see if I can find a patch that reliably crashes, the circumstances have to be just right it seems (and otherwise upload the one I'm using atm).

**Comment by falkTX** [comment]
Using this branch and https://github.com/falkTX/kuriborosu I did some quick checks to see if valgrind would detect any memory leaks or memory errors, and none were found.
One thing I had to tweak was the default values of the plugin. The enabled port should be set to 1 by default, otherwise on regular hosts the plugin is disabled by default.

Testing is as simple as building kuriborosu and running
```
valgrind ./bin/kuribu /path/to/midifile.mid out.wav http://moddevices.com/plugins/mod-devel/arpeggiator http://distrho.sf.net/plugins/Kars
```

**Comment by falkTX** [comment]
Changes have been pushed to the store, merging this.

**Pull request merged**
